name: OS Runners Demo

on: [push]

jobs:

  ubuntu-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Runner Info
        run: |
          echo "OS:"
          uname -a
          echo "Hostname:"
          hostname
          echo "Current User:"
          whoami

  windows-job:
    runs-on: windows-latest

    steps:
      - name: Print Runner Info
        run: |
          echo OS: %OS%
          hostname
          whoami
        shell: cmd

  macos-job:
    runs-on: macos-latest

    steps:
      - name: Print Runner Info
        run: |
          echo "OS:"
          uname -a
          echo "Hostname:"
          hostname
          echo "Current User:"
          whoami

  ubuntu-tools:
    runs-on: ubuntu-latest

    steps:
      - name: check installed tools
        run: |
          echo "Docker Version:"
          docker --version

          echo "Python Version:"
          python --version

          echo "Node Version:"
          node --version

          echo "Git Version:"
          git --version